// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class delete_userId_contact_iliski : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(delete_userId_contact_iliski));
        
        string IMigrationMetadata.Id
        {
            get { return "202204292318201_delete_userId_contact_iliski"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
