// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _contact_draft_trash_spam_read : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_contact_draft_trash_spam_read));
        
        string IMigrationMetadata.Id
        {
            get { return "202204111450094__contact_draft_trash_spam_read"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
