// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _contact_heading_addStringLenght1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_contact_heading_addStringLenght1));
        
        string IMigrationMetadata.Id
        {
            get { return "202203180938381__contact_heading_addStringLenght1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
