// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class added_admin_NewPassword : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_admin_NewPassword));
        
        string IMigrationMetadata.Id
        {
            get { return "202205092045566_added_admin_NewPassword"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
